### ISSUE TITLE
create a zurihac project proposal?

### ISSUE THREAD

**Issue by ghost** [Naproche/Naproche-SAD#25]
Consider creating a proposal of todo tasks for zurihac

**Comment by anfelor** [comment]
That sounds good! I am not sure whether I will attend the virtual Zurihac though and I am not aware of anyone else from our team who would be interested.. Maybe @adelon? I already worked on Naproche during last years MuniHac and there was some interest.

**Comment by ghost** [comment]
I am going to work on the lean pandoc reader this time, but maybe we can combine into a math proof tools group during next hackathon
